[package]
name = "lfs-rclone-rclone"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
lfs-rclone-domain.workspace = true
lfs-rclone-storage-port.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
sha2.workspace = true

[lints]
workspace = true
